ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YYYY';

/* Dropping existing tables to avoid conflicts */
DROP TABLE Advisor CASCADE CONSTRAINTS;
/* Creating the Advisor table */
CREATE TABLE Advisor (
    ADVISOR_ID INT CONSTRAINT ADVISOR_ID_PK PRIMARY KEY,
    ADVISOR_FNAME VARCHAR(50) CONSTRAINT ADVISOR_FNAME_NN NOT NULL,
    ADVISOR_LNAME VARCHAR(50) CONSTRAINT ADVISOR_LNAME_NN NOT NULL,
    ADVISOR_BIRTHDAY DATE,
    ADVISOR_POSITION VARCHAR(100),
    ADVISOR_DEPARTMENT VARCHAR(50),
    ADVISOR_ROOM_NUM VARCHAR(10)
);

/* Dropping existing tables to avoid conflicts */
DROP TABLE AdvisorTel CASCADE CONSTRAINTS;
/* Creating the AdvisorTel table */
CREATE TABLE AdvisorTel (
    ADVISOR_ID INT CONSTRAINT ADVISOR_ID_PK PRIMARY KEY,    
    ADVISOR_TEL_NUM VARCHAR(20),
    CONSTRAINT ADVISOR_ID_FK FOREIGN KEY (ADVISOR_ID) REFERENCES Advisor(ADVISOR_ID) ON DELETE CASCADE  
);

/* Dropping existing tables to avoid conflicts */
DROP TABLE Course CASCADE CONSTRAINTS;
/* Creating the Course table */
CREATE TABLE Course (
    COR_ID INT CONSTRAINT COR_ID_PK PRIMARY KEY,
    COR_DEGREE_TITLE VARCHAR(100),
    COR_DIRECTOR_NAME VARCHAR(100),
    COR_INT_TEL_NUM VARCHAR(20),
    COR_ROOM_NUM VARCHAR(10),
    COR_DEPT_NAME VARCHAR(50)
);

/* Dropping existing tables to avoid conflicts */
DROP TABLE Manager CASCADE CONSTRAINTS;
/* Creating the Manager table */
CREATE TABLE Manager (
    ALL_ACC_ID INT CONSTRAINT ALL_ACC_ID_PK PRIMARY KEY,
    HALL_MAGER_FNAME VARCHAR(50) CONSTRAINT HALL_MAGER_FNAME_NN NOT NULL,
    HALL_MAGER_LNAME VARCHAR(50) CONSTRAINT HALL_MAGER_LNAME_NN NOT NULL,
    CONSTRAINT ALL_ACC_ID_FK FOREIGN KEY (ALL_ACC_ID) REFERENCES Accommodation(ALL_ACC_ID) ON DELETE CASCADE
);

commit;
Alter session set NLS_DATE_FORMAT = 'DD-MON-YY'; 